# Generated by Django 5.2.4 on 2025-07-21 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("source", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "جدید"),
                            ("contacted", "تماس گرفته شده"),
                            ("converted", "تبدیل شده به مشتری"),
                            ("lost", "از دست رفته"),
                        ],
                        default="new",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="contactlog",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="group",
        ),
        migrations.RemoveField(
            model_name="task",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="task",
            name="user",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="user",
        ),
        migrations.AddField(
            model_name="customer",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="Interaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact_date", models.DateTimeField()),
                ("summary", models.TextField()),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.customer",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.lead",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Attachment",
        ),
        migrations.DeleteModel(
            name="ContactLog",
        ),
        migrations.DeleteModel(
            name="CustomerGroup",
        ),
        migrations.DeleteModel(
            name="Task",
        ),
    ]
